# Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.
Entrada = int(input('Informe um número inteiro: '))
print('{} * {} = {}'.format(Entrada, 1, Entrada*1))
print('{} * {} = {}'.format(Entrada, 2, Entrada*2))
print('{} * {} = {}'.format(Entrada, 3, Entrada*3))
print('{} * {} = {}'.format(Entrada, 4, Entrada*4))
print('{} * {} = {}'.format(Entrada, 5, Entrada*5))
print('{} * {} = {}'.format(Entrada, 6, Entrada*6))
print('{} * {} = {}'.format(Entrada, 7, Entrada*7))
print('{} * {} = {}'.format(Entrada, 8, Entrada*8))
print('{} * {} = {}'.format(Entrada, 9, Entrada*9))
print('{} * {} = {}'.format(Entrada, 10, Entrada*10))